# Study Matrix

In [2]:
import numpy as np

In [3]:
A = np.mat([[2,5,3], [3,5,5], [2,4,3]])
A

matrix([[2, 5, 3],
        [3, 5, 5],
        [2, 4, 3]])

In [4]:
# 행렬식
np.linalg.det(A)

0.99999999999999911

In [5]:
# 고유값
np.linalg.eig(A)

(array([ 10.92381154,  -0.11288743,  -0.81092411]),
 matrix([[-0.54593411, -0.90724148,  0.82275877],
         [-0.68439305,  0.14690743, -0.54957159],
         [-0.48328262,  0.39412066,  0.1450485 ]]))

In [6]:
B = np.mat([[3, 1], [1,3]])

In [9]:
# 고유값
d, P = np.linalg.eig(B)
d, P

(array([ 4.,  2.]), matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [15]:
D = np.diag(d)

In [16]:
P*D*P.I

matrix([[ 3.,  1.],
        [ 1.,  3.]])

In [17]:
P.I*D*P

matrix([[ 3., -1.],
        [-1.,  3.]])

In [18]:
P.I

matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]])

In [20]:
P2 = np.mat([[0.707, 0.707], [0.707, -0.707]])
P2

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [21]:
P2*D*P2.I

matrix([[ 3.,  1.],
        [ 1.,  3.]])

In [23]:
1/np.sqrt(2)

0.70710678118654746

In [26]:
import math

In [28]:
math.degrees(math.asin(0.707))

44.991348337162016